//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDemo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccountInfo
    {
        public int BankAccountInfoID { get; set; }
        public string BankName { get; set; }
        public string AccountNumber { get; set; }
        public string TypeOfAccount { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
