//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDemo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Home
    {
        public int HomeID { get; set; }
        public string Address { get; set; }
        public string Storied { get; set; }
        public string Area { get; set; }
        public string NakshapasDate { get; set; }
        public string NirmanSampannaDate { get; set; }
        public string Remarks { get; set; }
        public string Notes { get; set; }
    }
}
