//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDemo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Land
    {
        public int LandId { get; set; }
        public string District { get; set; }
        public string MunicipalityOrVdc { get; set; }
        public Nullable<int> WardNumber { get; set; }
        public string SheetNumber { get; set; }
        public string KittaNumber { get; set; }
        public string Area { get; set; }
        public string Type { get; set; }
        public string Note { get; set; }
    }
}
