//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDemo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class LastPagePara
    {
        public int LastPageParaID { get; set; }
        public string FirstPara { get; set; }
        public string SecondPara { get; set; }
        public string FormType { get; set; }
    }
}
