//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDemo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanBasedOnFund
    {
        public int LoanBasedonFundID { get; set; }
        public Nullable<decimal> ResidentialLoan { get; set; }
        public Nullable<decimal> RealStateLoan { get; set; }
        public Nullable<decimal> PersonalLoan { get; set; }
        public Nullable<decimal> ShareDepositLoan { get; set; }
        public Nullable<decimal> ESFULoan { get; set; }
        public Nullable<decimal> PoorAgriLoan { get; set; }
        public string VehicleloanWheels { get; set; }
        public Nullable<decimal> VehicleLoan { get; set; }
        public string RentVehicleType { get; set; }
        public Nullable<decimal> RentVehicleLoan { get; set; }
        public Nullable<decimal> OtherOneLoan { get; set; }
        public Nullable<decimal> OtherTwoLoan { get; set; }
    }
}
