//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDemo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectInvestment
    {
        public int ProjectInvestmentID { get; set; }
        public Nullable<decimal> TotalInverstment { get; set; }
        public Nullable<decimal> ApplicantInvestment { get; set; }
        public Nullable<decimal> LoanInvestment { get; set; }
        public Nullable<decimal> LoanPercentage { get; set; }
        public string Notes { get; set; }
    }
}
