//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDemo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int PropertyID { get; set; }
        public string Owner { get; set; }
        public string FatherName { get; set; }
        public string GrandFatherName { get; set; }
        public string Address { get; set; }
        public string RelationWithLoanSeeker { get; set; }
        public Nullable<bool> IsOrganized { get; set; }
        public string RegistrationNumber { get; set; }
        public Nullable<System.DateTime> RegisteredDate { get; set; }
        public string AuthorizedPerson { get; set; }
        public string RegisteredAt { get; set; }
        public string PAN { get; set; }
    }
}
